[package]
name = "flow-nft-gateway"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bastion = "0.4"
flow-sdk = "1.0.1"
futures = "0.3"
tokio = { version = "1.17.0", features = ["full"] }
